[workspace]
members = ["crates/*"]
package.edition = "2024"
resolver = "3"

[workspace.lints.clippy]
type-complexity = "allow"

[workspace.dependencies]
bevy_vpk = { path = "crates/bevy_vpk" }

bevy = "0.19"
avian3d = "0.7.0"
bevy_ahoy = { git = "https://github.com/andogq/bevy_ahoy.git", branch = "feat/bevy-0.19" }
bevy_enhanced_input = "0.26"
glam = "0.33"

# NOTE: Using fork that removes unnecessary noisy log lines
qbsp = { git = "https://github.com/eira-fransham/qbsp.git" }
vbsp = { git = "https://github.com/eira-fransham/vbsp.git" }
vdf-reader = { git = "https://codeberg.org/icewind/vdf-reader.git" }
vmdl = { git = "https://github.com/eira-fransham/vmdl.git" }
vmt-parser = { git = "https://codeberg.org/icewind/vmt-parser.git" }
vpk = { git = "https://github.com/eira-fransham/vpk-rs.git" }
vtf = { git = "https://github.com/eira-fransham/vtf-rs.git" }

anyhow = "1.0"
astcenc-rs = "0.2"
arrayvec = "0.7"
async-fs = "2.0"
cfg-if = "1.0"
clap = "4.5"
futures-io = "0.3"
image = "0.25"
itertools = "0.15"
pin-project = "1.0"
rand = "0.10"
rayon = "1.11"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"

[patch."https://github.com/eira-fransham/qbsp.git"]
qbsp = { path = "../qbsp" }

[patch."https://github.com/eira-fransham/vpk-rs.git"]
vpk = { path = "../vpk-rs" }

[patch."https://github.com/eira-fransham/vmdl.git"]
vmdl = { path = "../vmdl" }

[patch."https://github.com/eira-fransham/vbsp.git"]
vbsp = { path = "../vbsp" }

[patch."https://github.com/eira-fransham/vtf-rs.git"]
vtf = { path = "../vtf-rs" }

[patch."https://codeberg.org/icewind/vmt-parser.git"]
vmt-parser = { path = "../vmt-parser" }

# Remove spurious validation errors
[profile.dev.package.wgpu-types]
debug-assertions = false

[profile.bin-release]
inherits = "release"
strip = "symbols"
panic = "abort"
incremental = false
codegen-units = 1

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
